run:
  timeout: 5m
  go: '1.24' # Specify the minimum Go version
  concurrency: 4 # Number of parallel processes

linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sudoguy/kindle-bot)

linters:
  enable:
    - staticcheck # Finds bugs and performance issues
    - revive # Enforces code style and best practices
    - govet # Reports potential issues
    - unconvert # Detects unnecessary type conversions
    - unused # Identifies unused variables and constants
    - gosec # Checks for security issues
    - gocyclo # Calculates cyclomatic complexity of functions
    - dupl # Finds duplicate code
    - misspell # Detects spelling mistakes
    - unparam # Identifies unused function parameters
    - typecheck # Performs type checking
    - ineffassign # Identifies inefficient assignments
    - stylecheck # Enforces code style and best practices
    - gochecknoinits # Checks for init functions
    - copyloopvar # Detects loop variable references in closures
    - gocritic # Additional static analysis checks
    - nakedret # Identifies naked returns in functions
    - gosimple # Simplifies code
    - prealloc # Suggests preallocating slices
    - whitespace # Detects leading and trailing spaces
    - testifylint # Checks code using the testify package
    - sloglint # Checks for issues in code using the slog package
    - errorlint # Ensures proper error wrapping
    - exhaustive # Checks exhaustive switch statements for enums
    - gofumpt # Stricter Go formatting rules
    - gci # Enforces Go import order
    - thelper # Detects test helper functions without t.Helper
    - nilnil # Checks nil returns in error results
  fast: false
  disable-all: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment"
      linters:
        - revive
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
      text: "unused-parameter"
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
