services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kindle-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./books:/root/books
      - ./senders.json:/root/senders.json
