version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kindle-bot
    restart: always
    env_file: .env
    command: /root/bot
    volumes:
    - ./books:/root/books
